// USER ACTIONS
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILURE = 'LOGIN FAILURE'
export const LOGOUT = 'LOGOUT'

// WALET ACTIONS 
export const DEPOSIT_TO_WALLET = 'DEPOSIT_TO_WALLET';
export const DEPOSIT_TO_WALLET_SUCCESS = 'DEPOSIT_TO_WALLET_SUCCESS';
export const DEPOSIT_TO_WALLET_FAILURE = 'DEPOSIT_TO_WALLET_FAILURE';

export const WITHDRAW_FROM_WALLET = 'WITHDRAW_FROM_WALLET';
export const WITHDRAW_FROM_WALLET_SUCCESS = 'WITHDRAW_FROM_WALLET_SUCCESS';
export const WITHDRAW_FROM_WALLET_FAILURE = 'WITHDRAW_FROM_WALLET_FAILURE';

export const UPDATE_WALLET = 'UPDATE_WALLET';


// TRANSACTION ACTIONS
export const BUY_KOIN = 'BUY_KOIN';
export const BUY_KOIN_SUCCESS = 'BUY_KOIN_SUCCESS';
export const BUY_KOIN_FAILURE = 'BUY_KOIN_FAILURE';


// PURCHASE TRIGGERS
export const CREATE_TRIGGER_BUY_KOIN = "CREATE_TRIGGER_BUY_KOIN";
export const CREATE_TRIGGER_BUY_KOIN_SUCCESS = "CREATE_TRIGGER_BUY_KOIN_SUCCESS";
export const CREATE_TRIGGER_BUY_KOIN_FAILURE = "CREATE_TRIGGER_BUY_KOIN_FAILURE";

// BITCOIN TRANSACTIONS
export const GET_MY_TRANSACTIONS = "GET_MY_TRANSACTIONS";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_MY_TRANSACTIONS_FAILURE = "GET_MY_TRANSACTIONS_FAILURE";
export const GET_MY_TRANSACTIONS_SUCCESS = "GET_MY_TRANSACTIONS_SUCCESS";
export const GET_ALL_TRANSACTIONS_FAILURE = "GET_ALL_TRANSACTIONS_FAILURE";
export const GET_ALL_TRANSACTIONS_SUCCESS = "GET_ALL_TRANSACTIONS_SUCCESS";
