// USER ACTIONS
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILURE = 'LOGIN FAILURE'
export const LOGOUT = 'LOGOUT'

// WALET ACTIONS 
export const DEPOSIT_TO_WALLET = 'DEPOSIT_TO_WALLET';
export const DEPOSIT_TO_WALLET_SUCCESS = 'DEPOSIT_TO_WALLET_SUCCESS';
export const DEPOSIT_TO_WALLET_FAILURE = 'DEPOSIT_TO_WALLET_FAILURE';

export const WITHDRAW_FROM_WALLET = 'WITHDRAW_FROM_WALLET';
export const WITHDRAW_FROM_WALLET_SUCCESS = 'WITHDRAW_FROM_WALLET_SUCCESS';
export const WITHDRAW_FROM_WALLET_FAILURE = 'WITHDRAW_FROM_WALLET_FAILURE';

export const UPDATE_WALLET = 'UPDATE_WALLET';


// TRANSACTION ACTIONS
export const BUY_KOIN = 'BUY_KOIN';
export const BUY_KOIN_SUCCESS = 'BUY_KOIN_SUCCESS';
export const BUY_KOIN_FAILURE = 'BUY_KOIN_FAILURE';